// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

package me.n1ar4.fake.rpc;

public final class FakeServerRPC {
  private FakeServerRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_n1ar4_fake_rpc_RPCNull_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_n1ar4_fake_rpc_RPCNull_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_n1ar4_fake_rpc_RPCResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_n1ar4_fake_rpc_RPCResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_n1ar4_fake_rpc_RPCPort_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_n1ar4_fake_rpc_RPCPort_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014config.proto\022\021me.n1ar4.fake.rpc\"\t\n\007RPC" +
      "Null\"\'\n\007RPCResp\022\016\n\006status\030\001 \001(\t\022\014\n\004port\030" +
      "\002 \001(\005\"\027\n\007RPCPort\022\014\n\004port\030\001 \001(\0052\217\001\n\010RPCSt" +
      "art\022A\n\005start\022\032.me.n1ar4.fake.rpc.RPCNull" +
      "\032\032.me.n1ar4.fake.rpc.RPCResp\"\000\022@\n\004stop\022\032" +
      ".me.n1ar4.fake.rpc.RPCPort\032\032.me.n1ar4.fa" +
      "ke.rpc.RPCResp\"\000B$\n\021me.n1ar4.fake.rpcB\rF" +
      "akeServerRPCP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_me_n1ar4_fake_rpc_RPCNull_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_n1ar4_fake_rpc_RPCNull_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_n1ar4_fake_rpc_RPCNull_descriptor,
        new String[] { });
    internal_static_me_n1ar4_fake_rpc_RPCResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_n1ar4_fake_rpc_RPCResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_n1ar4_fake_rpc_RPCResp_descriptor,
        new String[] { "Status", "Port", });
    internal_static_me_n1ar4_fake_rpc_RPCPort_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_me_n1ar4_fake_rpc_RPCPort_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_n1ar4_fake_rpc_RPCPort_descriptor,
        new String[] { "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
