// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

package me.n1ar4.fake.rpc;

public interface RPCNullOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.n1ar4.fake.rpc.RPCNull)
    com.google.protobuf.MessageOrBuilder {
}
