// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

package me.n1ar4.fake.rpc;

public interface RPCPortOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.n1ar4.fake.rpc.RPCPort)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 port = 1;</code>
   */
  int getPort();
}
