// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

package me.n1ar4.fake.rpc;

public interface RPCRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.n1ar4.fake.rpc.RPCResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string status = 1;</code>
   */
  String getStatus();
  /**
   * <code>optional string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>optional int32 port = 2;</code>
   */
  int getPort();
}
